//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_Role
    {
    	public Auth_Role ToPOCO(bool isPOCO = true){
    		return new Auth_Role{
    			RoleId = this.RoleId,
    			RoleName = this.RoleName,
    			Description = this.Description,
    			RoleType = this.RoleType,
    			IsAvaiable = this.IsAvaiable,
    			CreateDate = this.CreateDate,
    			UpdateDate = this.UpdateDate,
    		};
    	}
    }
}
