//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_Permission
    {
    	public Auth_Permission ToPOCO(bool isPOCO = true){
    		return new Auth_Permission{
    			PermissionId = this.PermissionId,
    			ParentId = this.ParentId,
    			PermissionNo = this.PermissionNo,
    			PermissionName = this.PermissionName,
    			PermissionType = this.PermissionType,
    			ResourceUrl = this.ResourceUrl,
    			Target = this.Target,
    			SortIndex = this.SortIndex,
    			IsVisible = this.IsVisible,
    			IsAvaiable = this.IsAvaiable,
    			CreateDate = this.CreateDate,
    			UPdateDate = this.UPdateDate,
    		};
    	}
    }
}
