//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserThirdAccount
    {
    	public UserThirdAccount ToPOCO(bool isPOCO = true){
    		return new UserThirdAccount{
    			Id = this.Id,
    			UserId = this.UserId,
    			OpenId = this.OpenId,
    			Platform = this.Platform,
    			RegistTime = this.RegistTime,
    		};
    	}
    }
}
